# Generated by Django 6.1.1 on 2026-09-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
